Fix crash for selection
rosberry/PickL pull request #1
Opened 2020-06-01 02:24 UTC by artemnovichkov

- Rework project with framework-project-template
- Fix crash for selection (119-121 lines in PickL)

2020-06-17 09:00 UTC, Antowkos requested changes

2020-06-17 09:00 UTC, Antowkos commented on PickL.podspec
> +  spec.author       = { "Rosberry" => "develop@rosberry.com" }
And this is how the history become rewritten 😮

2020-06-17 09:01 UTC, Antowkos approved these changes

2020-06-17 09:05 UTC, disabled commented on PickL.podspec
> +  spec.author       = { "Rosberry" => "develop@rosberry.com" }
The end of an era.

2020-06-18 05:26 UTC, zhvrnkov approved these changes

2020-06-19 07:44 UTC, disabled approved these changes

2020-06-19 07:44 UTC, disabled commented on PickL/Sources/PickL.swift
> +        guard (0..<selectedRows.count).contains(component) else {
```suggestion
        guard selectedRows.indices.contains(component) else {
```

2020-06-19 10:11 UTC, merged